### ISSUE TITLE
/petcall or /pc is not working

### ISSUE THREAD

**Issue by ShrkSoft** [MyPetORG/MyPet#1653] opened 2024-01-19 02:53 UTC
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

When I type /pc or /petcall, the following error log is displayed on the console

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. get a pet
2. type /pc or /petcall

## Actual behavior
![mpcommanderr](https://github.com/MyPetORG/MyPet/assets/10734458/fa080285-97ae-45a8-b8e7-5718401c5b77)

## Additional context

[ticket.zip](https://d.kuku.lu/5suszny6e)

**Bukkit/Spigot/Bungee Build/Version:** PaperMC 1.20.4 Build 390

**MyPet Build/Version:** 3.12-SNAPSHOT-B1755

**Error:**
https://pastebin.com/S1YE2ikF

**Comment by Jakllp** [comment] 2024-01-19 10:45
As stupid as this sounds:  
I can't for the life of me reproduce this anymore.

I had this same issue exactly once during development of the 1.20.4 build, didn't change a thing, restarted the server and it has worked ever since.  
So the only advice I can give you right now is... Try restarting.  
If this doesn't help I'll need to investigate further (which will be interesting as I can't reproduce it)

**Comment by Jakllp** [comment] 2024-01-19 10:45
Also duplicate of #1652

**Comment by ShrkSoft** [comment] 2024-01-20 01:41
I restarted the server and the problem was fixed. 
Thank you.

**Closed** 2024-01-20 03:27 UTC
Labels: Bug
