### ISSUE TITLE
blaze getting falling damage

### ISSUE THREAD

**Issue by makegodhere** [MyPetORG/MyPet#1697] opened 2024-12-07 18:49 UTC
get blaze spawn
set hole under blaze
blaze getting falling damage

[3.12-SNAPSHOT-B1775](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1775)
paper 1.21.3

**Comment by Jakllp** [comment] 2024-12-08 10:00
Cannot reproduce, seems to be some other plugin interfering

**Comment by makegodhere** [comment] 2024-12-08 11:56
only mypet plugin in plugins list - same result

**Comment by Jakllp** [comment] 2024-12-08 12:13
Oh so you aren't even talking about pets here.  
Well that changes things  
I've retested, and think I kinda know the cause but don't know how to fix it yet.  
Thanks for the report

**Comment by Jakllp** [comment] 2024-12-09 08:07
Fixed in [3.12-SNAPSHOT-B1776](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1776)

**Closed by Jakllp** 2024-12-09 08:07 UTC
Labels: Bug
