### ISSUE TITLE
Piglin (child) pets steal equipement and won't stay put when told to

### ISSUE THREAD

**Issue by Felina-Lain** [MyPetORG/MyPet#1547] opened 2022-06-15 10:21 UTC
## Describe the bug

I got a baby-piglin pet, but when I try to make it sit still, I get both the "stay put" and "follow again" messages in the chat right away and it doesn't stay put.
On top of that, if I click the pet with a shield or any equipement in offhand, the pet will take it, AND if I had another item in my hand which it couldn't take, that item will just disappear.
exemple: potato in main hand, shield in offhand, sneak and click the pet, potatoes disappear, pet now has my shield, AND won't even stay put.

edit: Trying to place block with pet in the way also result in disappear blocks
Other pets just prevent placement, this one steal my blocks

## To Reproduce

- tame a baby piglin
- equip shield and an item in mainhand
- try to make pet sit still

## Expected behavior

Expected the same behaviour as other pet, which is to stay put and not make my items vanish. And not steal my shield.

**Bukkit/Spigot/Bungee Build/Version:**
Paper 1.18.2

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1691

**Comment by Jakllp** [comment] 2022-06-15 12:35
The potato (just gonna use your example here bc I think it's funny) might be client side or an actual bug, gonna test later.
Especially as it seems to be taking your offhand item.

Everything else is expected behavior.
Pets that can pick up items/have weapons (like Zombies, some Pillager-Types etc) will be given the item you're holding whilst sneaking and right clicking them.
You can get the items back by sneaking and using shears on them.

If you want them to sit you'll need to do it with an empty hand/item they can't pick up, which is were the afformentioned bug sets in.

Gonna investigate, thanks for reporting ^^

**Comment by Felina-Lain** [comment] 2022-06-15 14:52
> The potato (just gonna use your example here bc I think it's funny) might be client side or an actual bug, gonna test later. Especially as it seems to be taking your offhand item.
> 
> Everything else is expected behavior. Pets that can pick up items/have weapons (like Zombies, some Pillager-Types etc) will be given the item you're holding whilst sneaking and right clicking them. You can get the items back by sneaking and using shears on them.
> 
> If you want them to sit you'll need to do it with an empty hand/item they can't pick up, which is were the afformentioned bug sets in.
> 
> Gonna investigate, thanks for reporting ^^

Yeah, I knew about the pet equipement, but I didn't think it applied to offhand items? It never did for the other pets.
I also tried with other combination of holding things, to see what happened and maybe help narrow the problem origin down.
Here is the various results of my other tests
- mainhand empty, offhand with shield or tool: pet doesn't stay put, double chat message, take the shield/tool
- all hands empty, pet doesn't stay put, double chat message
- mainhand with non-pet item (potatoes), offhand empty, double chat message, pet doesn't stay put, disappear the potatoes
- And as mentioned above: mainhand with non-pet item, offhand with tool or shield, double chat message, pet doesn't stay put, steal the offhand item and disappear the mainhand item.

Also as mentioned in the edit, trying to place a block where the baby piglin pet is standing with consume the block but not place them, where other pet just block placing entirely (no block consumed) which I think might be coming from the same bug?

No worry, meanwhile I'll rely on my enderman instead XD

**Comment by Jakllp** [comment] 2022-06-15 15:12
Seems like the piglin is similar to the allay in 1.19 - problematic when it comes to interaction... (double messages... AHHH)

Will look into it soonish

**Comment by Jakllp** [comment] 2022-06-15 17:45
Also present in every version since 1.16
Also present with PiglinBrute

Pretty sure I know how to fix it

**Comment by Jakllp** [comment] 2022-06-15 18:04
Fixed in `3.12-SNAPSHOT-B1692`
With https://github.com/MyPetORG/MyPet/commit/8a8062d26bc16f38943dd1edfc8899531e55cf61

**Comment by Felina-Lain** [comment] 2022-06-15 20:50
> Fixed in `3.12-SNAPSHOT-B1692` With [8a8062d](https://github.com/MyPetORG/MyPet/commit/8a8062d26bc16f38943dd1edfc8899531e55cf61)

Fix works but not fully:
I can make the pet baby piglin stay put, but then it become impossible to right click him again to tell him to follow again
Can be bypassed by command /petcall so it's not as bad as the previous bug XD
It also no longer steal or disappear my items! Partially tamed the feral baby pig XD

**Comment by Jakllp** [comment] 2022-06-15 21:13
Oh ffs.
1.19 and 1.18 and seemingly 1.17 all have different behaviors for mobInteracts... AHH

**Comment by Jakllp** [comment] 2022-06-15 21:23
Okay no I'm stupid, forgot literally 2 lines of code_

**Comment by Jakllp** [comment] 2022-06-15 21:32
Now actually done in `3.12-SNAPSHOT-B1693`
with https://github.com/MyPetORG/MyPet/commit/2e134bf5be13325ff30907d01add0fe210611de3

**Closed by Jakllp** 2022-06-15 21:32 UTC
Labels: Bug

**Comment by Felina-Lain** [comment] 2022-06-16 19:55
Fully tamed feral baby pig! Hell yeah! thanks!!!
